preactjs/signals

- README.md
Signals look really exciting! Just fixing a small typo I noticed as I read through the readme.
> fix import typo in `README`

- README.md
I think you meant to set the `value`?
> fix `peak()` example in readme

- README.md
Unfortunately this was shared on hackernews instead of the announcement post. Hopefully just adding the link helps folks on HN understand more about the motivation to create signals etc.
> Add link to announcement in README.md

- .changeset/nice-timers-sort.md
- packages/core/src/index.ts
- packages/preact/src/index.ts
- packages/preact/src/internal.d.ts
- packages/preact/test/index.test.ts
Before we never unwrapped the signal passed into the element-attributes, this lead to the issue described in #74. We resolve this by assigning the prop to `signal.peek()`, this however leads to us losing the reference to the signal on `vnode.props[attribute-key]` which is used for the updater. To resolve the updater losing signal reference we switch the underlying data-structure to use an object of `{ key signal }` to save the reference.
While writing tests I noticed that the updater was never properly called as it would call the updater of the passed-in signal rather than the one we created with `createUpdater`, this is fixed by inheriting the `_updater` function to the props-signal.
Fixes https://github.com/preactjs/signals/issues/74
CSB Repro: …
> Correctly peek and replace value

- .changeset/silver-taxis-hammer.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.ts
- pnpm-lock.yaml
The HMR problem happens because `<Text data={signal} />` hadn't accounted for the `data` prop being given an entirely new Signal reference. This PR adds that logic.
> Fix swapping and HMR for signals when used as text

- README.md
- packages/core/package.json
- packages/preact/README.md
- packages/preact/package.json
- packages/react/README.md
- packages/react/package.json
None of the packages currently are published with ReadMes, which makes it difficult to browse on NPM.
This does 2 things:
- Copies root ReadMe to core on `prepublish`
- Splits the Preact & React content into their own ReadMes
I kept the intro blurb in each, not sure how others feel about that.
> chore: Splits README and ensures each pkg is published with one

- .changeset/neat-dingos-shake.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This is something that cannot occur through the public API. Ran into this whilst writing a custom adapter for another project.
We were missing a guard check before trying to unmark a signal, that checks if it was marked in the first place. We should bail out if it wasn't marked as needing an update.
> Fix internal API able to unmark non-marked signals

- .changeset/two-mails-sip.md
- packages/core/src/index.ts
This fixes a memory leak caused by all signals being addressable from our internal `ROOT` signal. We never ended up using the root signal, and removing it means computed graphs within components get nicely GC'd when unmounted.
> Remove root signal

- .changeset/selfish-cameras-play.md
- mangle.json
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/preact/src/index.ts
- packages/react/src/index.ts
This PR addresses an issue where a stale conditional value would not be refreshed. In the example below the `b` signal wasn't updated upon re-activation.
```js
const a = signal(0);
const b = computed(() => a.value);
const c = computed(() => (a.value > 0 ? a.value : b.value));
```
As a bonus point this makes our activation logic a bit simpler.
This was reported on twitter: https://twitter.com/artalar_dev/status/1569210487233028096
> Fix stale value when conditionally accessing stale signal

- packages/core/src/index.ts
- packages/preact/src/index.ts
- tsconfig.json
Missed this variable in #127 . Our tooling should fail on build if it detects unused variables. This PR addresses that.
> Throw on build for unused variables

- .changeset/mighty-pianos-end.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
Just some suggestions I noticed while reading over the code. Mostly typo fixes in comments, but I also thought using the parameter name dep instead of sub in those arrow functions made more sense, and then I noticed that in one of the tests, the code didn't seem to align with the comment at the top of the test, it looks like that eSpy function should be reading d.value.
Thanks for building this library. I'm looking forward to trying it out some more.
Note: This PR is a redo of https://github.com/preactjs/signals/pull/123
> Small fixes to core

- .github/workflows/compressed-size.yml
- docs/vite.config.ts
This changes the names of the `import()` bundles from `index.[hash].js` to `{basic,react,nesting}.[hash].js`, where the first part of the name is the directory (in the case of an import for an `index.*` file.
This should fix the randomization issue with our CI size action.
> [demo] Fix entry bundle names

- .changeset/quick-ladybugs-cry.md
- packages/core/src/index.ts
Currently `.subscribe()`'s type is marked as `subscribe(fn: (value: T) => () => void)` ("`.subscribe`takes a function that returns a function, `.subscribe` itself returns `void`").
This PR changes it to `subscribe(fn: (value: T) => void): () => void` ("`.subscribe` takes a function, and `.subscribe` itself returns a function").
> Fix .subscribe's type

- .changeset/curvy-moose-shave.md
- packages/core/src/index.ts
As discussed in #104, I'm going to try and split the improvements into multiple smaller PRs.
All of the tests pass, but this does slightly change the behavior, so I hope it doesn't break anybody's code.
> Changing batch to use a single flag instead of a counter

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
This pull request adds a basic devcontainer setup:
* pnpm installed
* Chromium installed for running tests
* ESLint and Prettier extensions for VSCode
I went with Alpine, as I have the most experience with it and it had Chromium etc. nicely packaged for both x86_64 and aarch64. Tested with a M1 based Mac.
> Add a basic devcontainer

- packages/react/src/index.ts
- packages/react/test/index.test.tsx
Fixes #125
Fixes #135
Fixes #70
This PR tracks `ReactCurrentOwner` separately from `ReactCurrentDispatcher` since the former is not guaranteed to be populated when `ReactCurrentDispatcher` is mutated. This is very evident from #125, and you can verify by running against a production build of React. Annoyingly, this behavior is different than that of a development build of React.
Additionally, signals' updaters are mutated on subsequent runs since there are multiple dispatchers during the lifecycle of a component, and holding on to a stale dispatcher can break the re-rendering mechanism (it wouldn't do anything).
> **Note**: The relevant dispatcher states are [invalid](https://github.com/facebook/react/blob/c156ecd483b4adc8e16254b8cab3ee735e893271/packages/react-reconciler/src/ReactFiberHoo …
> fix(react): track owners separately, mutate updaters with dispatcher

- .changeset/popular-avocados-sip.md
- packages/preact/src/index.ts
- packages/react/src/index.ts
This switches the Preact integration to automatically render Signals as Text, rather than walking the Virtual DOM tree to to convert Signals to JSX. The technique is the same as what we use in the React integration. I had avoided using this technique for Preact because Preact 10 adds internal properties to VNodes, which would cause shape changes for Signals used in JSXText positions, however it turns out there's an easy fix: add `__b:1` to the Signal prototype to trigger Preact's [existing VNode re-use cloning behavior](https://github.com/preactjs/preact/blob/d7a433ee8463a7dc23a05111bb47de9ec729ad4d/src/diff/children.js#L77).
I also updated the React integration to include `configurable:true` in the property descriptors we install into `Signal.prototype`. Folks should never have two …
> Improve Signal->Text rendering in Preact

- .changeset/unlucky-rocks-return.md
- docs/demos/animation/index.tsx
- docs/demos/animation/style.css
- docs/demos/index.tsx
- docs/vite.config.ts
- packages/preact/src/index.ts
- packages/preact/src/internal.d.ts
In Preact 10, new `VNode` instances are passed to the `DIFF` hook on every render. In the previous prop bindings implementation, this was causing signal prop values to be bound on every VDOM render, leaking memory and doing unnecessary work.
This new approach replaces Signal prop values with their peek()'d current values in order to allow Preact to render those props using its standard setProperty mechanics, and the Signal instances are stored in a new property attached to the element VNode. After a VNode is diffed (`options.diffed`), if it has Signals stored in this new property, their DOM bindings are set up using an Updater that is stored on the DOM element itself - this works because DOM elements are stable references in Preact 10, whereas VNodes are not.
The implementation in this PR …
> [preact] Optimize performance of prop bindings

- .changeset/tiny-numbers-argue.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
Just checking if a signal is "active" or not before refreshing it's value is not enough. During batching an active signal can be invalidated and we _must_ refresh its value when read from.
This fixes an accidental regression introduced in #127 .
Fixes #145
> Fix stale invalidated signals inside batch

- packages/core/src/bench.ts
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request rewrites the core to avoid allocating Sets, Maps and Arrays on the fly. The implementation uses linked lists of nodes that contain both the source (signal) and target (computed/effect) of dependency-subscription pairs. The aim was to facilitate constant-time subscribe/unsubscribe operations without sets.
Currently this breaks the Preact/React integrations, as the core internals have changed quite a bit.
Computed signals evaluate their values lazily whenever their `.value` is accessed or `.peek()` is called.
Computed signals also lazily subscribe to be notified when their dependencies change _only_ when the computed itself already has subscribers. This is done so that computed signals that aren't currently (direct or indirect) dependencies of some effects or other …
> Implement core without Sets, Maps, Arrays etc.

- .changeset/heavy-turkeys-relate.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request adds support for auto-disposing nested effects. With the following setup:
```ts
const a = signal("a");
const b = signal("x");
const e = effect(() => {
console.log("outer effect", a.value);
effect(() => {
console.log("inner effect", a.value + b.value);
});
});
// Console: outer effect a
// Console: inner effect ax
```
Now if we run the outer effect again the previous inner effect is auto-disposed:
```ts
a.value = "b";
// Console: outer effect b
// Console: inner effect bx
```
If we only update the `b` signal only the latest version of the inner effect runs:
```ts
b.value = "y"
// Console: inner effect by
```
When we dispose the outer effect then the inner effect is also disposed:
```ts
e();
a.value = "c";
// Nothing in the console
```
Note that only immediate containing …
> Support auto-disposing nested effects

- .changeset/strong-kiwis-drive.md
- packages/preact/src/index.ts
- packages/react/src/index.ts
- pnpm-lock.yaml
Currently running effects is a bit of a pitfall imho, or we run them globally outside of the function-scope, or we have to wrap them with a `useMemo`/`useEffect`/... This lead me on the path of creating a small utility function that abstracts this. When people want to use a global `signal`/`effect` they can import from the `core` package, however when they want a component-specific signal they leverage `useSignal`. It's here where I saw a discrepancy, we have a utility to help provide a signal but no utility for the effect.
Here comes the introduction of `useSignalEffect` it basically wraps an `effect` with `useEffect` and holds a stable ref to the callback being passed to the `useSignalEffect` so we don't have to bother adding dependencies to the array of the used `useEffect`. Currently …
> Proposal: use signal effect

- mangle.json
This pull request tunes the settings in mangle.json to make the core faster (by ~50% in a specific benchmark) and bundle size smaller (about -20 B).
> This also illustrates how it's a good idea to run the benchmarks with the production builds, as Terser seems to be able to have a big impact in the (micro level) performance depending on the compression + mangling settings.
For some reason mangling core's Node._source to Node.s adds a significant performance hit (on a small micro-benchmark). Renaming it to Node.S instead helps to boost performance by 20% or so.
Another setting causing another ~20% performance hit is the "evaluate" compression option. Turning it off helps performance, but raises the build bundle size a bit.
To compensate for that turning off "conditionals", "loops" and …
> Tune mangle.json

- .changeset/twelve-suits-smell.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request adds the support for disposing currently running effects. The reasoning for this is that it's convenient, and ends up saving a couple of bytes in some bundle versions.
Disposing the effect while running just delays the full disposal until the run has finished.
> Allow disposing currently running effects

- packages/core/test/signal.test.tsx
This pull request adds some tests for `batch()`, focusing on how `batch()` handles different return values and thrown errors from batch callbacks and effects.
> Add batch tests

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
While the #160 is still a bit in the flux we can start by ES5-ifying parts that didn't cause problems. This might also make it a bit easier to avoid merge conflicts.
> Convert Effect to an ES5 style class

- package.json
- patches/@babel__plugin-transform-typescript@7.19.1.patch
- pnpm-lock.yaml
This applies the fix from https://github.com/babel/babel/pull/14946 to our project and we can drop it as soon as a new version of that babel plugin is released.
_Note: Had to add it as an explicit dependency, otherwise pnpm would not patch it._
> Patch @babel/plugin-transform-typescript to not drop export

- package.json
- packages/core/src/index.ts
- patches/@babel__plugin-transform-typescript@7.19.1.patch
- pnpm-lock.yaml
This pull request implements the Effect, Computed and Signal classes as ES5 classes.
Added a workaround for a weird performance cliff that I encountered with Node.js 18.9.0. The workaround itself is in commit 64d0ab0844a4d50ee09d564b8748127e8a957049. For some reason the TypeScript compiled version was faster than the hand-rolled ES5 classes when running this benchmark:
```ts
import * as core from "@/preact/signals-core";
{
const count = core.signal(0);
const double = core.computed(() => count.value * 2);
core.effect(() => double.value + count.value);
core.effect(() => double.value + count.value);
core.effect(() => double.value + count.value);
console.time("core");
for (let i = 0; i < 20000000; i++) {
count.value++;
double.value;
}
console.timeEnd("core");
}
```
In the end it turned out …
> Implement Effect, Computed and Signal classes as ES5 classes

- .changeset/sour-snails-whisper.md
- mangle.json
- packages/preact/src/index.ts
- packages/preact/src/internal.d.ts
This pull request refactors the Preact integration to modestly reduce the size:
* Modify property change listeners to use the signals' own change tracking to track whether the signal that the property should listen has changed.
* Keep the state in previously kept in WeakSets and a WeakMaps Component's own props. The updater is stored in `_updater` and `hasHookState`, `hasPendingUpdate` and `hasComputeds` are tracked in the bitset `_updateFlags`. The names get mangled to `_$u` and `_$f`, respectively.
> Refactor Preact integration

- packages/core/src/index.ts
This pull request adds `/** @internal */` annotations above the Signal and Computed functions to hide them from the build .d.ts files.
> Hide Signal and Computed functions from output .d.ts files

- mangle.json
- packages/core/src/index.ts
This pull request splits Computed value refreshing and `.peek()` into two separate phases, which in turn allows flattening the call stack and removing a recursing try-catch section inside `Computed.peek()`.
In the end this seems to make the code much less sensitive to specific compression & mangling setting, so the "evaluate" compression setting could be enabled again without any performance penalty. Also the previous weird performance issue (solved by wrapping Compute.prototype creation into an IIFE) didn't manifest itself anymore, so the IIFE could be removed. These make the bundled code size smaller, and the benchmarks seem to give a bit better results as well.
> Refactor how signal values are revalidated

- .changeset/tidy-buses-do.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/preact/src/index.ts
- packages/react/src/index.ts
This pull request implements effect cleanup functions. An effect callback can return a function that's then run the next time the effect either gets rerun or disposed. This pull request also converts the `useSignalEffect` hook for the Preact and React integrations to use effect cleanups.
The `effect(compute: () => void)` signature is modified to `effect(compute: () => unknown)`:
```ts
const s = signal(0);
const dispose = effect(() => {
if (s.value === 0) {
effect(() => () => console.log("hello"));
} else {
effect(() => () => console.log("what a"));
}
return () => console.log("world");
});
s.value++; // Prints "hello" & "world"
dispose(); // Prints "what a" & "world"
```
Apart from testing basic functionality, the tests try to cover several corner cases and specific behaviors:
* The …
> Implement effect cleanups

- packages/preact/src/index.ts
- packages/preact/src/internal.d.ts
- packages/preact/test/index.test.tsx
This is an alternative to the duplicate prop assignment fix in #177 ([60b41b9](https://github.com/preactjs/signals/pull/177/commits/60b41b9fe105bc21fcea00d10b85caf3c3c92328)). Instead of detecting `renderToString` vs `render` to do Signal-only updates on the client, it allows VDOM updates to render all props (including peek'd signal values), then uses the rendered prop values to determine whether the next Signal-based update should be skipped. Signal updates also mutate their associated VNode props to have the received value, bypassing future VDOM re-rendering of a prop if its value has not changed.
> Alternative solution to duplicate prop assignment

- .changeset/chatty-buckets-try.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request modifies `Signal.subscribe(fn)` to run `fn` in an untracked context. The subscribe function was implemented with `effect`. Therefore if `fn` accessed some signal values it caused the surrounding effect to start following those signals too.
Added also relevant tests for `.subscribe`.
> Run .subscribe callbacks in an untracked context

- packages/core/package.json
This pull request add `"sideEffects": false` to the package.json of @preact/signal-core.
> Add "sideEffects": false to core's package.json

- packages/core/test/signal.test.tsx
This pull request fixes the test "should allow disposing the effect multiple times", spotted by @cevr. Luckily the test still passes, but now it at least does something 😀
> Fix "should allow disposing the effect multiple times" test

- .changeset/rude-bananas-drop.md
- packages/preact/package.json
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
- pnpm-lock.yaml
> preact-render-to-string invokes optins,unmount but has no _dom

- .changeset/grumpy-experts-cover.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
After the v1.2.0 update, effects didn't check whether their direct dependencies have actually changed before rerunning. For example in the following scenario the effect would run twice:
```ts
const s = signal(0);
const c = computed(() => {
s.value;
return 0;
});
effect(() => {
console.log("effect running");
c.value;
}); // Console: effect running
s.value = 1; // Console: effect running
```
This pull reuses the computed signal dependency checks for effects. It also adds tests specific to this feature, as well as tests tangentially related parts to effect & computed signal dependency checking.
> Reuse computed signal dependency checks also for effects

- .changeset/rare-bulldogs-sin.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request fixes the case when an effect cleanup throws. There was a test for this case, but it should have been more thorough. The test is stricter now as well.
> Fix effect disposal when cleanup throws

- packages/core/test/signal.test.tsx
This pull request adds three new tests for Signals Core:
* Test that an effects and computed signals don't force dependencies get recomputed unnecessarily.
* Test computed signal behavior right after getting its first active subscriber.
> Add more tests

- .changeset/tall-onions-deny.md
- packages/core/src/index.ts
This pull request modifies the dependency version change check used by computed & effect. Before the change each dependency's `._refresh()` was called before checking the dependency's version number. After this change the version number is checked first, then `._refresh()` is called, and then the version number is checked again. In practice this allows the dependency checks break the loop earlier, avoiding calls to `_refresh()` for a) plain signals that have changed and b) computed values that get repeated reads.
The following benchmark demonstrates the impact in a scenario that contains both a) and b):
```ts
import * as core from "@preact/signals-core";
const count = core.signal(0);
const double = core.computed(() => count.value * 2);
core.effect(() => double.value + count.value); …
```
> Optimize dependency value change checks by allowing earlier exists from the loop

- karma.conf.js
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- tsconfig.json
This pull request adds the following things:
* Tests that computed signals are indeed garbage collectable when they have no listeners (either they never had or the listeners have been disposed).
* Fix for effect disposal, releasing the effect function that may still hold a reference to the surrounding scope, and through that to a computed signal. I noticed this behavior after writing the second test.
Points that probably need special attention during review:
* Modified Karma config to add `--js-flags=--expose-gc` to the Chromium launch arguments. This was done to enable forcing the garbage collection via `globals.gc`/`window.gc`. The tests are get skipped if `global.gc`/`window.gc` is not available, so that it's easier to run them in another contexts.
* Added `"lib": ["ES2021.WeakRef"]` …
> Dispose effects more thoroughly, add tests for computed() GC behavior

- packages/react/src/index.ts
- packages/react/src/internal.d.ts
As I mentioned in https://github.com/preactjs/signals/issues/155, tracking the current owner is unstable and doesn't work in production. I think the purpose of that was to keep a unique updater for each component. I found that can also be done by just using the rerender callback as the key for the map since it is consistent and unique to each component's render.
This change also changes the invalid hook check to just "Invalid" which works in React Native too (its hook warnings are slightly different).
The tests still pass, and this method is working well in Legend-State (https://github.com/LegendApp/legend-state/blob/main/src/react/enableLegendStateReact.ts#L70) in production and React Native.
> Change mapping updaters to owners to map to the reducer, fixing not working in production

- .changeset/funny-geese-hear.md
- mangle.json
> Fix hook names being mangled

- .changeset/pretty-students-look.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request simplifies effect change checking by removing the OUTDATED flag usage from effects. The flag itself can't be completely removed from the codebase, as computed signals still use it. Still, there are some delicious byte size savings gained from this change.
The OUTDATED flag became unnecessary after the changes introduced in #205.
As a nice side-effect the effect cycle detection is now more accurate. There is a new test case for that. The test case does collide with #231, and should be removed if/when that pull request is merged. The code simplifications are still valid regardless.
> Simplify effect change checking (and make effect cycle detection more accurate as a side-effect)

- .changeset/brown-wombats-brush.md
- packages/react/package.json
- packages/react/src/index.ts
- packages/react/src/internal.d.ts
- packages/react/test/index.test.tsx
- pnpm-lock.yaml
From Preact Slack discussion 😄 
`useSyncExternalStore` is the suggested way by React to subscribe to state that lives outside of React which is compatible with their concurrent mode and time-slicing features.
This PR also removes the need to track current owner because hooks run in the context of the current owner so there is no need to really do it. Please check the comments in the code.
> React: Replace useReducer with useSyncExternalStore

- .changeset/strange-beans-attend.md
- packages/react/src/index.ts
Importing the `use-sync-external-store/shim` from the `signals.mjs` fails with `ERR_UNSUPPORTED_DIR_IMPORT` because the shim doesn't have an `exports` map in `package.json` so it needs to be imported explicitly including the `/index.js` file.
Resolves #237 
Tested by installing `@preact/signals-react: 1.2.0` and manually modifying the dist `signals.mjs` import 😛
> React: Fix ERR_UNSUPPORTED_DIR_IMPORT when importing `use-sync-external-store/shim` #237

- .changeset/breezy-ants-trade.md
- packages/react/src/index.ts
A Regular `Map` is being used to hold a map of proxied components , this can lead to unbounded memory leaks if for example a component is created within another.
ie:
```
function OutterComponent(props) {
function InnerComponent(props) {...}
return <InnerComponent />
}
```
Leads to a new entry in the map on each render of `OutterComponent` with no way to collect. `WeakMap` should do the trick here.
> Use WeakMap to hold proxy map in react

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
Mainly typo fixes, but also made a change to [this test](https://github.com/preactjs/signals/blob/main/packages/core/test/signal.test.tsx#L752). I noticed that setting `s.value = 2;` after `e._dispose();` wasn't actually testing if the dispose function worked because the value of `s` was already 2 at that point. I verified this by commenting out the `e._dispose();` line and the tests still passed. So I changed that line to `s.value = 3;` which now makes the test only pass if `e._dispose();` is called.
Also, I edited a part of [one of the test diagrams](https://github.com/preactjs/signals/blob/main/packages/core/test/signal.test.tsx#L1457) from `D <- we don't listen to C` to `D <- we don't listen to D`, but I wasn't sure if that diagram should actually be changed more. I noticed that the …
> Fix typos and other small changes

- package.json
- packages/core/package.json
- packages/preact/package.json
- packages/react/package.json
Add the description to `package.json`, so something shows up when I look at dependencies on github.
> add description to package.json

- .changeset/short-paws-listen.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
- packages/react/src/index.ts
- packages/react/test/index.test.tsx
When we refactored to use the new cleanup approach in September, we accidentally removed useSignalEffect's cleanup functionality. This adds it back, and adds tests for it. The types were never changed, so they're correct now that this functionality is restored.
Fixes #281.
> Bugfix: useSignalEffect cleanup not called

- packages/core/src/index.ts
This pull request fixes issue #274 spotted by @modderme123. The root cause for the exponential slowdown was the fact that the _unsubscribe method was always run for every computed/signal that's dropped from the dependency graph - even when there was no need. This in turn caused an avalanche of unnecessary work.
Before this change the [Stackblitz benchmark](https://stackblitz.com/edit/preact-signals-slowdown) took ~15.8 seconds to complete on my machine. After this change it took around 3 milliseconds.
Huge thanks to @modderme123 for spotting this, and for the excellent issue description. The Stackblitz example made the reproduction phase trivial 👍
> Fix #274: Avoid cascading unsubscribes

- packages/core/src/index.ts
Currently, the dependencies are in reverse order of use when it needs to do the `cleanupSources`. There is quite some time spent doing so.
While doing some experiments on a project on mine I found out that it'd perform faster if the dependencies order didn't need to be built in reverse order. The way to achieve this is by doing two things:
1. On `prepareSources`, make `target._sources` point to the tail instead of the head
2. On `cleanupSources`, walk from tail to head **while** dropping old dependencies and reverting to the rollback node
The advantage of doing so is that, if there are no nodes to drop (nodes with `version: -1`) then we're just walking the list backwards without setting any properties.
New nodes are added directly to the tail, and the new node becomes the tail. If old …
> Performance improvement: Preserve order of sources

- .github/workflows/main.yml
- .github/workflows/release.yml
Resolve #310 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: |
echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
```
**TO-BE**
```yml
run: |
echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
```
> Replace deprecated command with environment file

- .changeset/polite-ghosts-yell.md
- packages/core/src/index.ts
- packages/preact/src/index.ts
The `effect` function signature is changed in order to more closely match the `useSignalEffect` signature, and also remove the ambiguity of the `unknown` typing.
Edit: useSignalEffect cleanup was resolved in #282
> Add typing for effect cleanup

- .changeset/thin-coats-wash.md
- packages/react/src/index.ts
- packages/react/test/index.test.tsx
The latest version of @preact/signals-react not work with forwardRef when use with `{xxx.value}`.
This is the demo({count} works, but {count.value} not):
https://codesandbox.io/s/preact-signals-react-forwardref-not-work-k5pcry?file=/src/App.js
This PR fixes this.
> Support forwardRef in @preact/signals-react

- .changeset/metal-emus-design.md
- packages/core/src/index.ts
- packages/react/src/index.ts
- packages/react/src/internal.d.ts
- packages/react/test/index.test.tsx
This PR updates the typing of the React signal adapter to enable the text binding. General refactors to the React adapter typing are also included.
The reason for this change is because the implementation of the React signal adapter [supports direct text binding](https://github.com/preactjs/signals/blob/55d5becbb41c2faec62b9588937f8c74f0d65152/packages/react/test/index.test.tsx#L34-L40).
A couple `@ts-ignore` were also added to the core package to account for how Typescript interprets ES5 classes.
Fixes #261
> Type Signal as valid React JSX

- .changeset/happy-pants-rhyme.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
From Slack discussion, this PR disallows side-effects in `computed`. That is, setting signal's values:
```ts
const c = computed(() => a.value++)
```
I used a bit flag instead of `instanceof` operator because it's faster to check if a bit is set than walking the prototype to lookup for a constructor. I initially thought to add a new `_type` property to Signal but it also seems a waste of space/memory if it's only used to check if a Signal is a computed type.
> Disallow side-effects in computed

- .changeset/thick-news-raise.md
- .github/workflows/main.yml
- package.json
- packages/react/test/index.test.tsx
This PR adds an additional test command and run in CI that runs our test suite against React's production build.
I'm working on the react adapter and there are different behaviors between React's dev and prod builds so I'm adding this capability now so any future work I do doesn't regress functionality against React's prod build.
> Run test suite agains React's production build

- .changeset/angry-papayas-accept.md
- package.json
- packages/react/package.json
- packages/react/src/index.ts
- packages/react/test/index.test.tsx
- packages/react/test/react-router.test.tsx
- packages/react/test/utils.ts
- pnpm-lock.yaml
Revert our react integration back to setting up signal subscription tracking by watching changes in the ReactCurrentDispatcher instead of proxying function Component calls in createElement so it works with more ecosystem libraries such as react-router-dom.
Check the comment in the source for a deeper discussion of the implementation details and choices.
Fixes #251 
Fixes #330
> Revert react integration to tracking current dispatcher

- .changeset/fluffy-pillows-shout.md
- packages/react/package.json
Is there any reason we can't support ^16.14.0? [According to npmfs.com](https://npmfs.com/package/react/16.14.0/), the react 16.14.0 package is the first version that contains the `jsx-runtime` and `jsx-dev-runtime` files so it shouldn't cause any errors. Running the tests locally on 16.14.0 pass as well.
> Allow react ^16.14.0 as a peer dependency

- packages/react/src/index.ts
useSyncExternalStore documentation is currently linked to old React documentation. I updated it to the new React documentation link.
> Update useSyncExternalStore doc link

- .github/workflows/main.yml
- packages/react/test/index.test.tsx
- packages/react/test/react-router.test.tsx
- packages/react/test/utils.ts
React 16 and React 18 have different enough behavior I'd like to run tests against both to ensure no regressions
> Run test suite against React 16

- .changeset/config.json
- .devcontainer/devcontainer.json
- .github/workflows/compressed-size.yml
- README.md
- docs/demos/react/tsconfig.json
- docs/package.json
- mangle.json
- package.json
- packages/core/package.json
- packages/core/test/signal.test.tsx
- packages/preact/README.md
- packages/preact/package.json
- packages/react/package.json
- scripts/node-13-exports.js
- tsconfig.json
We had `useTabs: true` in our prettier config which overrode our `.editorconfig` to use spaces in `json` files. I've removed the `useTabs` in the package.json prettier config so `.editorconfig` is used instead. I've also reformatted all the code so it's consistent.
> Remove prettier override so editorconfig is applied

- packages/core/test/signal.test.tsx
- packages/preact/test/index.test.tsx
- packages/react/test/browser/updates.test.tsx
Specifically tests creating and passing computed between components
> Add tests verifying the behavior of nested effects and computeds

- .changeset/chilled-cheetahs-grin.md
- packages/core/package.json
- packages/preact/package.json
- packages/react/package.json
- packages/react/runtime/package.json
In all three of the packages, `package.json#exports.umd` has been referencing the incorrect path for the UMD bundles since release (should've been `x.min.js`).
However, seeing as how I can't see a single complaint relating to this, and I'm not aware of any tools that actually consume it (would love to know if there are tools that do), I elected to remove the entries. Saves us from making a breaking change in the future if we were to alter that entry in any way.
> refactor: Remove non-functional `package.json#exports.umd`

- .changeset/tasty-cooks-own.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
- pnpm-lock.yaml
When a component utilises signals and one `useContext` that works with `useState` then context updates won't propagate as they are stopped by this condition
> Allow for context to propagate to components using context

- .changeset/plenty-rabbits-tickle.md
- packages/react/runtime/package.json
I forgot to include the mangle.json pointer in the new package.json so some property names weren't being properly mangled. 
Note: no tests fail because currently `@preact/signals-react` bundles the runtime package inside of it's bundled output and those properties are mangled - it doesn't import from `/runtime`. I left that as is for now since the `/runtime` package is intended to be an internal detail that will likely change in the future. I discovered this while working on the babel transform which does import from `/runtime` directly.
> Fix internal property names

- packages/react/README.md
There is missing documentation regarding the TypeScript error in React when the signal object is used directly in JSX.  This requires wrapping the object in a React Fragment (see https://github.com/preactjs/signals/issues/323).
This PR adds a note about the React Fragment requirement.  The Preact 'Render Optimization' content was copied with changes to code example and added note.  This updated code sample was tested and working the correctly with React.
https://codesandbox.io/s/preact-signals-in-react-test-mzfv8x\?file\=/src/LogCount.tsx
> docs: add React fragment note

- .github/workflows/compressed-size.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- pnpm-lock.yaml
It appears some of our Netlify builds (e.g. in PR #375) are failing due to pnpm version mismatch. This PR upgrades our version to the latest (v8) to fix them.
> Upgrade to pnpm v8

- .changeset/dirty-geese-learn.md
- README.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/preact/README.md
- packages/preact/src/index.ts
- packages/react/README.md
- packages/react/src/index.ts
Resolves https://github.com/preactjs/signals/issues/378
As mentioned in the proposal this allows us to write effects that essentially aren't re-executed by the signals that get accessed in the function body of `untracked`.
Allowing functionality like
```js
function reaction(sender, listener) {
effect(() => {
const value = sender();
untracked(() => {
listener(value);
});
}
}
```
> Added `untracked` function

- .changeset/forty-points-marry.md
- packages/react-transform/package.json
To make it easier to use this library in existing projects with various babel versions
> Lower required babel version required as a peer dependency

- README.md
It looks like a paragraph explaining how to use `peek()` had gotten duplicated into the bottom of the new section for `untracked(fn)`.
> Remove duplicated paragraph in Readme for `untracked`

- .changeset/wild-spies-glow.md
> Fix wrongly named property

- .changeset/cyan-swans-serve.md
- .changeset/lucky-radios-deny.md
- package.json
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
- pnpm-lock.yaml
When inserting a new import statement, we need to register it with Babel's scope tracking so future usages of the import are properly tracked to this declaration.
I've also removed CJS support currently since we don't have any tests for it and I'm uncertain if the maintenance burden if worth it. Open to suggestions.
> Register newly inserted import statement as a declaration in Babel scope

- .changeset/little-vans-develop.md
- package.json
This fixes "useMemo undefined" error when using `useSignal` hook with UMD scripts.
The UMD builds of `preact/hooks` package will attach itself to the global `window.preactHooks` when using CDN, while `@preact/signals` is searching for `window.hooks` and cause this problem.
There is also some messages about this in microbundle's output log:
```
$ pnpm run build:preact
> pnpm _build --cwd packages/preact && pnpm postbuild:preact
> microbundle --raw --globals @preact/signals-core=preactSignalsCore "--cwd" "packages/preact"
No name was provided for external module 'preact/hooks' in output.globals – guessing 'hooks'
```
Here is a minimal reproduction page demonstrating the issue.
https://stackblitz.com/edit/preact-signals-cdn
```
Uncaught TypeError: Cannot read properties of undefined (reading …
```
> fix: add microbundle global for preact/hooks package

- .changeset/modern-glasses-repair.md
- packages/react-transform/README.md
Added 'module:' prefix to readme to babel recognized plugin correctly
> fixed tranform readme

- .changeset/proud-dogs-study.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
"All" mode transforms all components to be reactive to signals. You can still opt-out using `/** @notrackSignals */`.
Related: #412
> Add an "all" mode to the react transform 

- packages/preact/test/index.test.tsx
- packages/react/test/browser/updates.test.tsx
Adding a test to capture expected behavior of passing a model containing signals through context, to ensure as I make changes to the react adapter, etc. I don't break this pattern
> Capture expected behavior of passing signals through context

- karma.conf.js
- package.json
Local tests run a lot faster now since we aren't running babel on all of React DOM
> In tests, skip Babel on node_modules when not down leveling

- .changeset/fresh-panthers-explain.md
- .changeset/lovely-moons-beam.md
- packages/react-transform/src/index.ts
- packages/react/runtime/src/auto.ts
- packages/react/runtime/src/index.ts
As suggested by @developit, disable `useSignals` when the auto tracking hook is installed since components can instead rely on that behavior. Also, add `useSignals` to the SignalValue component to fix it when used with the babel transform
> Fix rendering signals as text when using react-transform

- .changeset/twenty-pillows-scream.md
- packages/react-transform/package.json
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
- packages/react/test/browser/updates.test.tsx
- pnpm-lock.yaml
- test/browser/nodeGlobals.js
To assist in deploying and debugging the react signals transform, add the ability to log what functions are transformed by the plugin. Also includes the option to log what functions look like Components but aren't transformed cuz they either don't appear to use Signals or don't contain JSX
> [react-transform] Add debug logging to inspect what components are transformed by plugin

- .changeset/stupid-badgers-float.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/helpers.ts
Component's like
```js
var render = function App() { ... }
```
will now by transformed by the babel plugin since the function expression has a valid Component name.
Before it would not be transformed because the variable name was not valid because the variable name begins with a lowercase letter.
> Use function expression name if it has one

- .changeset/metal-snakes-hide.md
- packages/core/src/index.ts
This syntax (export { type Foo }) insta-breaks the build for any project using versions of TS earlier than v4.5. Verified locally that this change fixes the build for earlier versions while not breaking it for later versions.
I believe the only scenario in which this change could impact tree-shaking is if someone is only importing the `ReadonlySignal` type in a project that doesn't otherwise use signals, which seems unlikely.
> Removes backward-incompatible type export.

- .changeset/wise-toes-joke.md
- packages/react/src/index.ts
> Fixed typescript error from resolving unspecified in exports map .ts file

- .changeset/mighty-crews-burn.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/browser/e2e.test.tsx
- packages/react-transform/test/node/helpers.ts
- packages/react-transform/test/node/index.test.tsx
- packages/react/runtime/src/auto.ts
- packages/react/runtime/src/index.ts
- packages/react/runtime/test/browser/useSignals.test.tsx
- packages/react/test/shared/utils.ts
This PR adds tests and supported for nested `useSignals` calls when combined in components & hooks. We generally have two different mechanisms to call useSignals: 1) using react-transform & 2) calling `useSignals()` directly in a component or hook.
To support mixing and matching these scenarios, I've added parameter to `useSignals()` that specifies how this invocation is being used. It primarily exists for the transform to tell `useSignals` it is gonna be manually closed by the code the transform emits.
Using this parameter, when I new store starts, it can examine the previous store and properly handle closing it out or "capture and restoring it" once the current store finishes. See the comment in `runtime/src/index.ts:_start()` for a detailed description of the exact behavior here.
> Improve mixing useSignals called in hooks and components together

- .changeset/funny-falcons-pretend.md
- .changeset/warm-apples-applaud.md
- docs/vite.config.ts
- package.json
- packages/react-transform/README.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/browser/e2e.test.tsx
- packages/react-transform/test/node/helpers.ts
- packages/react-transform/test/node/index.test.tsx
- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.ts
Before this change, importing `@preact/signals-react` would invoke side effects that hook into React internals to automatically track signals. This change removes those side effects and requires consumers to update their code to continue using signals in React.
To continue the "auto-tracking" mechanism, users can import `@preact/signals-react/auto` to keep the previous mechanism in place.
I'm also adding support for the comment `@useSignals` and `@noUseSignals` to be consistent with the hook people can use to track signals: `useSignals()`.
> Remove auto tracking using React internals from signals-react package

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request fixes an issue with multiple levels of mixed `effect` and `untracked` calls:
```ts
import { signal, effect, untracked } from "@preact/signals-core";
const s = signal(0);
untracked(() => {
effect(() => {
untracked(() => {
console.log(s.value); // <-- s.value gets tracked while inside untracked(...)
});
});
});
// 0 gets printed to the console
s.value = 1;
// 1 gets printed to the console
```
The expected behavior is that the effect should not run when `s.value` is set to `1`, because `s.value` was only used inside `untracked`. Therefore the effect should not become dependent on `s.value`.
The root cause is that only the outermost level of nested `untracked()` calls sets the evaluation context to undefined (which disables tracking). The fix is to unconditionally set the …
> Fix: always reset the evaluation context upon entering an untracked block

- packages/core/src/index.ts
This pull request uses the `untracked()` function to simplify the implementation of the `Signal.prototype.subscribe` method. The functionality of the method stays the same.
Byte savings fall between 2 and 19 bytes, depending on the bundling output format:
```
Before this PR:
1487 B: signals-core.js.gz
1352 B: signals-core.js.br
1513 B: signals-core.mjs.gz
1378 B: signals-core.mjs.br
1498 B: signals-core.module.js.gz
1369 B: signals-core.module.js.br
1561 B: signals-core.min.js.gz
1421 B: signals-core.min.js.br
After this PR:
1481 B: signals-core.js.gz
1350 B: signals-core.js.br
1494 B: signals-core.mjs.gz
1363 B: signals-core.mjs.br
1488 B: signals-core.module.js.gz
1352 B: signals-core.module.js.br
1557 B: signals-core.min.js.gz
1414 B: signals-core.min.js.br
```
The downside is that …
> refactor: use untracked to implement Signal.prototype.subscribe

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request 
* Inline the `cycleDetected` function. The downside is that the error message is now repeated in multiple places of the codebase. The next change helps with this by removing one of these repeats.
* Reimplement `Signal.prototype.peek` that works for both Signal and Computed instances, so that the specialized `Computed.prototype.peek` implementation can be removed. This also removes one place where `cycleDetected` was used.
A couple of new tests are included to test that computeds' `peek()` still throws errors when the computed function fails.
In aggregate these changes save between 10 and 29 bytes, depending on the output format:
```
Before:
1481 B: signals-core.js.gz
1350 B: signals-core.js.br
1494 B: signals-core.mjs.gz
1363 B: signals-core.mjs.br
1488 B: …
```
> refactor: inline cycle errors & use a shared .peek() implementation for signals and computeds

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request is a continuation for #523, where the `Signal.prototype.subscribe` method was implemented using the `untracked()` function, saving some bytes. 
Inlining the `untracked()` call saves bytes for most output formats and solves the tree-shaking downside mentioned in #523.
```
Before:
1481 B: signals-core.js.gz
1350 B: signals-core.js.br
1494 B: signals-core.mjs.gz
1363 B: signals-core.mjs.br
1488 B: signals-core.module.js.gz
1352 B: signals-core.module.js.br
1557 B: signals-core.min.js.gz
1414 B: signals-core.min.js.br
After:
1474 B: signals-core.js.gz
1333 B: signals-core.js.br
1497 B: signals-core.mjs.gz
1364 B: signals-core.mjs.br
1486 B: signals-core.module.js.gz
1353 B: signals-core.module.js.br
1550 B: signals-core.min.js.gz
1412 B: signals-core.min.js.br
```
A new test …
> refactor: inline Signal.prototype.subscribe implementation

- .changeset/dull-pumas-carry.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request allows setting a `signal`'s value inside a `computed`. Previously the following code was not allowed and raised an error with the message "Computed cannot have side-effects":
```ts
const s = signal(0);
const c = computed(() => {
s.value = 1;
});
c.value; // Error: Computed cannot have side-effects
```
This suggested change is based on Slack discussions (TL;DR: there may be legitimate use-cases that the side-effect limitation blocks / the "regular" cycle detection might be enough for preventing runaway modification loops) and submitted here for further evaluation. /cc @developit @marvinhagemeister 
This change saves some bytes from the output bundles:
```
Before this change:
1481 B: signals-core.js.gz
1350 B: signals-core.js.br
1494 B: signals-core.mjs.gz
1363 B: …
```
> Allow setting a signal value inside a computed

- README.md
- packages/core/src/index.ts
This pull request adds minor bits of documentation.
* Add a comment to the source code why ES5-style prototypes are used instead of ES6-style classes.
* Add documentation mentioning effect cleanups in README.md.
* Fix README.md's section order that was not in sync with the table of contents in the beginning of README.md.
> docs: document effect cleanups & comment why ES5-style prototypes are used

- mangle.json
- packages/core/src/index.ts
This pull request adds rudimentary JSDocs for all exported members of the core module.
The JSDoc contents are mostly mixed & matched from the README.md and the Preact website.
I renamed the `compute` arguments to `fn` and the internal `_compute` properties to `_fn` to align with external documentation. The mangle.json needed to be updated accordingly, with some unrelated formatting changes by the automation.
> docs(core): add JSDocs for exported module members

- .github/workflows/compressed-size.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
This pull request updates most actions used in the CI workflows, and makes the following changes:
* Use actions/setup-node's builtin dependency caching for pnpm as described [here](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data).
* Related to the change described above, run pnpm/action-setup before actions/setup-node.
* Remove the `run_install: false` option from pnpm/action-setup, as it's the default.
> build(actions): update actions, use actions/setup-node's builtin caching

- .changeset/cool-pianos-fly.md
- .changeset/neat-carrots-drop.md
- .changeset/perfect-onions-remember.md
- .changeset/rare-colts-smash.md
This pull request adds changesets for #512, #529, #531 and #535. The changesets use the "pr: #N" syntax introduced in https://github.com/changesets/changesets/pull/535 for signaling which pull requests they're related to.
All the changesets apply only to the core, _except_ the changeset for #535 ("Publish packages with provenance statements") which introduces a patch bump for all of the packages.
> chore: add changesets for recent pull requests

- .github/workflows/release.yml
- package.json
This pull request modifies the changeset version bump script to also update the pnpm lockfile when needed. The solution is based on https://github.com/changesets/action/issues/203#issuecomment-1483000632.
This hopefully solves https://github.com/preactjs/signals/pull/528#issuecomment-1999126668, i.e. preact-signals-demo deployments failing when internal dependencies are bumped.
> build: update pnpm lockfile on changeset version bumps

- .changeset/nine-fishes-leave.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request restores the stricter types for effect callbacks and effect cleanup functions introduced in #249. Core tests needed to be modified slightly to accommodate these typing changes.
These stricter types were later changed back to allowing both effect callbacks and effect cleanup functions return `unknown`. It is convenient to allow anything to be returned, especially when writing tests like `effect(() => s.value++)`. On the other hand stricter types can be useful for catching e.g. attempts to have asynchronous effect handlers, which the core does not support (`effect(async () => { ... })`).
It's debatable whether this change would warrant a patch or major release. I've tentatively chosen a patch changeset, as the previous related changes were also patch changes.
> fix(core): Restore stricter effect callback & cleanup function types

- .changeset/gorgeous-moose-hope.md
- packages/core/test/signal.test.tsx
- packages/react/runtime/src/index.ts
- packages/react/runtime/test/browser/suspense.test.tsx
- packages/react/test/shared/utils.ts
I have not managed to reproduce this in tests, since it only seems to happen in React Native, and I believe only with Hermes. In this environment, layout effects are flushed after a microtask (or synchronously?), and rendering can be triggered synchronously from them (via setState/useSyncExternalStore/etc). This means the "close current tracking context" operation we schedule after a Promise tick doesn't happen before the next render begins, which can cause an unmanaged useSignals() call to be left "open".
I've added a `useLayoutEffect()` to unmanaged `useSignals()` to address this, which just works by closing any open tracking context when React finishes the current render (as defined by the time at which React begins to execute effects).
As part of this, I also had to tweak `store.f()` …
> Fix out-of-order effect error when suspending in React Native

- .changeset/sharp-rockets-march.md
- packages/react/runtime/src/auto.ts
Resolves #576 
This should point people in the right direction 😅
> chore(signals-react): throw error when auto-tracking with React 19

- .changeset/tame-bobcats-invent.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
This was a bit more complex than initially anticipated due to how we have chosen to transform, I wanted to make as little change as possible so here goes...
- This adds a check to our `memberExpression` that zooms out towards the component definition
- If along the way we encounter any hooks like `useEffect`/... we bail
- When we reach the highest scope we signal this as a component in need of signals
Fixes https://github.com/preactjs/signals/issues/552
Supersedes https://github.com/preactjs/signals/pull/553
> fix(react-signals-transform): Support nested functions accessing signals

- .changeset/wet-radios-clap.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
Noticed we threw an error for non-ESM modules, so added support for that as we are exporting a CJS build of our react-bindings either way.
CC @andrewiggins not sure if you opted out here for a reason
Fixes https://github.com/preactjs/signals/issues/575
> feat(react-transform): Suppport require syntax in our babel transform

- .changeset/seven-seahorses-cry.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/preact/test/index.test.tsx
- packages/react/src/index.ts
- packages/react/test/shared/updates.tsx
Avoid inheriting from signal in ReadonlySignal so we can't accidentally widen the type by doing `const computed: Signal<any> = useComputed(() => {})`, in widening this type we would lose the `readonly` aspect of the value property effectively making it a mutable signal.
Fixes https://github.com/preactjs/signals/issues/585
> Adjust ReadOnlySignal so we cant widen the type

- .changeset/empty-chefs-repeat.md
- packages/react/runtime/src/index.ts
- packages/react/test/shared/updates.tsx
As we have no good way to align this with i.e. `act` for testing purposes, ... I reckon it's better we just revert this for react.
> Revert raf aligned effects for react

- .changeset/ninety-beans-compare.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
- packages/react/test/shared/updates.tsx
This also converts our synchronous DOM updates to be animation-frame aligned, this will make them execute in parallel and when the browser is prepared for it.
Let's draw out the ideal scenario we want to create:
- effects that end up in a setState get executed synchronously so these updates are immediately added in the render queue
- signal-effects are deferred by an animation-frame
- TextNodeUpdates are deferred by an animation-frame
- AttributeNodeUpdates are deferred by an animation-frame
Now we can be sure that Preact updates take presedence over our normal DOM updates.
One thing I am unsure of is the following https://github.com/preactjs/signals/blob/main/packages/preact/src/index.ts#L92-L100 whether we can reliably make this also deferred as currently it's synchronous, we could just …
> Raf aligned dom updates

- .changeset/great-geese-play.md
- packages/react/runtime/src/index.ts
> fix(signals-react): use isomorphic layout

- .changeset/selfish-ravens-sit.md
- packages/preact/src/index.ts
As per slack - simplify text update patch to avoid using new internals (`_source`).
> simplify text update patch

- .changeset/tidy-rivers-fly.md
- packages/preact/src/index.ts
This changes the delay for property updates to be a double micro-task, we got a report that in examples like
```jsx
const App = () => {
const text = useSignal('')
const style = useSignal('')
const callback = (input) => {
text.value = input.currentTarget.value
if (text.value >= 5) { style.value = 'display:none;'}
}
return <input style={style} onInput={callback} value={text} />
}
```
In the above case the user would be able to type 6 characters while we have actually already made the input dissapear.
> Change delay to double microtask for prop updates

- .changeset/thirty-lies-destroy.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
> fix: Replace body so fast-refresh function caching works

- .changeset/silver-crabs-sniff.md
- packages/preact/src/index.ts
- packages/preact/src/internal.d.ts
https://github.com/preactjs/signals/pull/630 but for 1.x.x
> Backport state settling

- .changeset/unlucky-impalas-grow.md
- mangle.json
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
This pull request fixes a case in the Preact bindings where effects created for optimized text updates didn't get disposed. This in turn could cause intermediate computeds to never get garbage collected as long as their dependencies didn't get garbage collected.
There's a new test for this scenario. The test passes after applying this PR.
There is also an additional modification to mangle.json: The `pure_effects` option is now set to `false`, because `.value` accesses for signals are not pure. This caused the minifier to remove and reorder important `.value` accesses in a way that internal effects weren't always depending on them properly, causing the production tests to fail.
> fix: Ensure that text effects get disposed

- .github/workflows/compressed-size.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- pnpm-lock.yaml
Every time I opened a branch I had a lot of pending changes, this intends to resolve that by bumping the pnpm version to 9.12
> Upgrade pnpm

- .changeset/new-lions-grin.md
- packages/preact/src/index.ts
Resolves https://github.com/preactjs/ecosystem-ci/actions/runs/13334317934/job/37245954930
> Use vnode._dom

- .changeset/selfish-news-perform.md
- packages/preact/src/index.ts
When a page is hidden because the user is on a different tab but it received i.e. a webhook we still want effects to run. This PR ensures that by installing a 100ms timeout as animation frames don't run for non-visible pages.
> Use afterNextFrame for hidden origins

- .changeset/cuddly-geese-matter.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
Fixes https://github.com/preactjs/signals/issues/665
We forgot that an Array can't be optimised rendered, this is considered not a valid element but also isn't text. We used to catch this with `nodeType` checks https://github.com/preactjs/signals/blob/%40preact/signals%401.3.2/packages/preact/src/index.ts#L97
> Fix array signals when used as jsx

- .changeset/beige-cherries-applaud.md
- packages/preact/package.json
Relates to https://github.com/preactjs/preact/issues/4747
> Correctly set peer of signals

- .changeset/dry-lemons-play.md
- packages/preact/src/index.ts
Similar to https://github.com/preactjs/preact/pull/4750
> Reduce RAF timeout

- .changeset/tough-rice-cover.md
- README.md
- mangle.json
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/preact/src/index.ts
- packages/react/runtime/src/index.ts
Resolves https://github.com/preactjs/signals/issues/351
Resolves https://github.com/preactjs/signals/issues/428
This adds a second argument to `signal` which are the `options`, currently this adds two properties, watched and unwatched. These will most likely serve third party libraries a lot more than first party consumers.
- watched will trigger when the first subscriber subscribes to a signal
- unwatched will trigger when the last subscriber unsubscribes from a signal
The second parameter can in the future be used for other RFC's in our pipeline like the equality function. The addition of this parameter is in line with the TC39 proposal for browser-native signals https://github.com/tc39/proposal-signals
I opted not to add this to `computed` for the time being as the signal itself is the …
> Add watched and unwatched

- .changeset/breezy-cherries-type.md
- packages/core/src/index.ts
It should still be optional even when providing an object
> Loosen up types for (un)watched

- README.md
- packages/core/README.md
- packages/core/package.json
- packages/preact/README.md
- packages/react/README.md
Does a couple things, all related to the our ReadMes:
- Firstly, adds all headings to the "Table of Contents" for each ReadMe
- The new signal utils were missing from that in both the React & Preact integrations. The React integration was also missing a few others as well.
- Creates a new ReadMe for core, splitting it away from the repo root
- Previously the ReadMe in the repo root was copied into the core lib prior to publish, but I suppose that created an odd situation in which the Core package had links to the React & Preact integrations (up until https://github.com/preactjs/signals/pull/634/commits/7f729c4ec1a961ed58b6c9d1f98bb75a5a6b2513, that is). Whilst very helpful to have in the repo root here on GitHub, it did make less sense to be in the published documentation for …
> docs: Split root ReadMe & core ReadMe, flesh out ToC in React & Preact ReadMes

- .changeset/sixty-snails-raise.md
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
Enable the Babel plugin to register accessing `.value` during destructuring as signals usage. This will end up correctly registering components like the following
```jsx
const X = (props) => {
const { x: { value: mySignalValue } } = props
}
```
The result is that X will correctly have `useSignals` and react to changing to the x-signal.
> support destructured signal access

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- docs/vite.config.ts
- karma.conf.js
- package.json
- packages/react-transform/src/index.ts
- packages/react/test/browser/react-router.test.tsx
- pnpm-lock.yaml
This PR updates prettier + applies formatting to the files. I've set the `trailingComma` option to `es5` to reduce the amount of changes.
> chore: update prettier

- package.json
- pnpm-lock.yaml
- scripts/mangle-plugin.mjs
- vitest.config.mjs
Adds vitest and associated scripts which will not succeed yet, as we
have no projects.
**This is a base branch**. We will merge all other vitest migration branches
into this one, and ultimately merge this into main when _everything_ is
migrated.
> test: add vitest prep

- .changeset/odd-tigers-remember.md
- packages/preact/src/index.ts
The callback to `useMemo` is assumed to be pure during HMR and will be re-triggered. This in turn broke the `useSignal` hooks HMR as they used side-effectful callbacks.
> fix: make prefresh hmr integration easier

- .changeset/old-cycles-swim.md
- extension/src/components/Graph.tsx
- packages/react-transform/src/index.ts
- packages/react-transform/test/node/index.test.tsx
Related to #727
We inject a name for every computed/signal we encounter this makes the debugging a lot more convenient, in addition to that this adds a block to every react component so we can track the signals used within it.
> Add signal names

- extension/src/components/Graph.tsx
- extension/src/components/SettingsPanel.tsx
- extension/src/components/UpdateItem.tsx
- extension/src/models/ConnectionModel.ts
- extension/src/models/SettingsModel.ts
- extension/src/panel.tsx
- extension/src/types.ts
- packages/debug/src/devtools.ts
> Abstract into settings-store and fix component-name assignment

- packages/debug/src/devtools.ts
- packages/preact/src/index.ts
draft for now since we're not sure if we want this yet
something along the lines of this could be useful though, to see what actually rendered. most signals end up in text nodes, so we don't really know the context of the component that actually rendered it. this could help w/ that
> feat(extension): display first component parent in render info
