- README.md
Sorry, deleted comment on PR as I needed to reassure myself this was in fact correct 😅
"signals" here is singular ("...how _it_ came to be", emphasis mine) as we're referring to `preact-signals` so we need "solves".
> fix; Grammar issue in readme

- .changeset/large-bags-smile.md
- packages/react/package.json
> fix: Correct invalid React peerDep versions

- karma.conf.js
I shouldn't code late at night!
> Remove console.logs in karma.config.js

- .changeset/wet-grapes-eat.md
Apologies, forgot to add it when merging #130
> Add missing changeset for #130

- .changeset/smooth-coins-warn.md
- packages/core/package.json
- packages/preact/package.json
- packages/react/package.json
See: https://github.com/preactjs/signals/issues/111#issuecomment-1246016116
> Move "types" field to the top for TS

- .changeset/honest-tomatoes-walk.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
> Fix computed updated despite no dependencies having changed

- package.json
- pnpm-lock.yaml
> Add missing changeset dependency

- mangle.json
Fix mangling of new Componen properties introduced in #171.
> Don't mangle new Component helper props

- .changeset/lemon-hornets-nail.md
- packages/preact/src/index.ts
- packages/preact/test/index.test.tsx
> Fix unable to set SVG attribute from signal

- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
This pull request is a minor refactoring of the Computed._refresh method, reducing bundle bytes and adding code comments. A new test for effects, mirroring the "should conditionally unsubscribe from signals" test for computed signals, is also added.
> Minor cleanups and comment + test additions

- karma.conf.js
> fix: ut coverage not work on *.ts

- packages/core/test/signal.test.tsx
This pull request adds `Computed.peek()` its own section in the tests, moves some existing tests there and adds some new ones.
> Add tests for Computed.peek()

- packages/preact/README.md
Re: https://github.com/preactjs/preact-www/pull/929
> docs: Clarify that signals + dom props != two-way data binding

- packages/react/README.md
> Whenver -> Whenever in README

- README.md
Computed and Effect Anchor Tags were Linked To incorrect reference
> Updated Readme Link to Valid Tag

- .changeset/kind-months-give.md
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
Resolves https://github.com/preactjs/signals/issues/276
Resolves https://github.com/preactjs/signals/issues/258
> Support `toJSON` on a signal

- .changeset/slow-dancers-serve.md
- packages/react/src/index.ts
https://twitter.com/impatienceisav1/status/1648811982059888640
It'd be nice if the React team provided any form of package exports here
> fix: Resolve full useSyncExternalStore path

- .changeset/flat-oranges-promise.md
- packages/react/README.md
In parallel, I'm also gonna explore some alternate implementations that offers different tradeoffs so teams can choose the best option for their project.
> Add note about tradeoffs in current React integration

- .husky/pre-commit
- global.d.ts
- package.json
- packages/core/src/index.ts
- packages/core/test/signal.test.tsx
- packages/react-transform/src/index.ts
- packages/react/runtime/src/auto.ts
- packages/react/runtime/src/index.ts
- pnpm-lock.yaml
Also fix our lint-staged and husky setup so this happens on pre-commit locally
> Reapply formatting to the repo

- CONTRIBUTING.md
- packages/core/package.json
- packages/preact/package.json
- packages/react-transform/package.json
- packages/react/package.json
- scripts/pack-all.mjs
Add a CONTRIBUTING file with the steps to release signals as well was specify in the package.json what files/dirs should be included in the package
> Add release guide and specify files to include in package

- .github/ISSUE_TEMPLATE/bug-report.md
~~Not quite sure how I buggered this up, weird~~ Ah crap, copied the link from my branch when making it 🤦
> fix: Issue template link

- .changeset/new-emus-check.md
- packages/core/src/index.ts
- packages/preact/src/index.ts
- packages/react/runtime/src/index.ts
Resolves https://github.com/preactjs/signals/issues/532
> chore(signals): add default undefined type

- .changeset/rude-gorillas-rush.md
Fixes https://github.com/preactjs/signals/issues/590
> Bump react for ReadonlySignal

- .changeset/orange-moles-trade.md
- packages/react/utils/src/index.ts
Same as https://github.com/preactjs/signals/pull/701 but for the React utility
> [TS] Narrow types for Show utility in React

- vitest.config.mjs
We were quickly going to end up with too many sub-configs, and all sorts
of problems with extending the various configs.
This switches to a single root config which globs each of the monorepo
packages instead.
the `MINIFY=true` stuff doesn't quite work yet but we can fix in a follow up PR
> fix: move to using a root vitest config

- extension/src/components/Graph.tsx
- extension/src/components/Header.tsx
- extension/src/components/SettingsPanel.tsx
- extension/src/components/UpdateItem.tsx
- extension/src/components/UpdateTreeNode.tsx
- extension/src/components/UpdatesContainer.tsx
- extension/src/models/UpdatesModel.ts
- extension/src/panel.tsx
- extension/styles/panel.css
> Allow folding updates

- .changeset/tricky-pots-confess.md
- packages/core/src/index.ts
> Remove internal annotation to avoid confusing TS

- .changeset/tough-windows-teach.md
- packages/debug/src/devtools.ts
> Fix complex updates
